version: "3"
services:

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    expose:
      - 6379
    networks:
      internal_services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    expose:
      - 5432
    env_file:
      - ./config/cadence.env
    networks:
      internal_services:

  icecast2:
    build:
      dockerfile: ./cadence/icecast2.Dockerfile
    image: kenellorando/cadence_icecast2:latest
    container_name: icecast2
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/icecast.xml:/etc/icecast/cadence.xml
    networks:
      external_services:
      stream_delivery:

  liquidsoap:
    build:
      dockerfile: ./cadence/liquidsoap.Dockerfile
    image: kenellorando/cadence_liquidsoap:latest
    container_name: liquidsoap
    restart: always
    volumes:
      - ./config/liquidsoap.liq:/etc/liquidsoap/cadence.liq
      - /music:/music
    depends_on:
      - icecast2
    expose:
      - 1234
    networks:
      internal_services:
      stream_delivery:

  cadence:
    build:
      context: ./cadence
      dockerfile: ./cadence.Dockerfile
    image: kenellorando/cadence
    container_name: cadence
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./config/cadence.env
    volumes:
      - /music:/music
    depends_on:
      - icecast2
      - liquidsoap
      - redis
      - postgres
    networks:
      internal_services:
      external_services:

networks:
  external_services:
    driver: bridge
  internal_services:
    driver: bridge
  stream_delivery:
    driver: bridge
